baseURL = "https://siir.pub"
languageCode = "en-us"
title = "SIIR"
theme = "notrack"
newContentEditor = "nvim"
mainSections = ["blog"]
# disqusShortname = "example"
paginate = 4

[params]
  author = "SIIR"
  siteHeading = "Security Intelligence and International Relations" # defaults to author
  favicon = "horse.png" # Adds a small icon next to the page title in a tab
  showBlogLatest = true
  mainSections = ["blog"]
  showTaxonomyLinks = false
  nBlogLatest = 4 # number of blog post on the home page
  blogLatestHeading = "Latest"
  showReadingTime = true
  showProgressBar = true
  description = "A site dedicated to Security Intelligence and International Relations" # Add this line for default description
  defaultOGImage = "img/horse4.jpg"  # Adjust the path as necessary


  [params.social]
    github = "ihateprogramming88"
    email = "Anaxandreas@protonmail.com"
    rss = "rss won't use the value you give it so you can put anything here"



[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"

[markup]
  [markup.highlight]
    style = "dracula"
    noClasses = false
    guessSyntax = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]

